services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  nuxt-app:
    image: node:18-bullseye
    container_name: nuxt
    working_dir: /app
    volumes:
      - ./cinema:/app
    ports:
      - "3001:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install && npm run dev"
    links:
      - nodesocket-app

  nodesocket-app:
    build:
      dockerfile: ./Dockerfile
      context: ./back/cinema-node
    container_name: nodesocket
    volumes:
      - ./back/cinema-node:/app
    working_dir: /app
    command: >
      bash -c "npm install
      && nodemon index.js -L"
    ports:
      - "3727:3727"

  laravel-app:
    build:
      dockerfile: ./Dockerfile
      context: ./back/cinema-backend
    container_name: laravel
    ports:
      - "8001:8000"
    volumes:
      - ./back/cinema-backend:/var/www/:cached
    working_dir: /var/www/
    depends_on:
      - db
    entrypoint: ["bash", "/var/www/entrypoint.sh"]
